name: health_tracker
description: A new Flutter project.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: 3.0.0
  cached_network_image: 3.1.0+1
  font_awesome_flutter: 10.1.0
  google_fonts: 2.2.0
  intl: 0.17.0
  json_path: 0.3.1
  page_transition: 2.0.4
  shared_preferences: 2.0.11
  timeago: 3.1.0
  cloud_firestore: ^3.1.14
  file_picker: ^4.5.1
  open_file: ^3.2.1
  path_provider: ^2.0.9
  animated_text_kit: ^4.2.1
  geolocator: ^8.2.1
  geocoding: ^2.0.4
  firebase_database: ^9.0.15
  firebase_storage: ^10.2.17
  firebase_messaging: ^11.4.1
  web3dart: ^2.3.3
  http: ^0.13.4
  url_launcher: ^6.1.3
  flutter_local_notifications: ^8.1.0
  rxdart: ^0.27.1
  dio: ^4.0.6


dev_dependencies:

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/
